/**
 * Forytography Shop + Client Galleries — Cloudflare Worker
 * -----------------------------------------------------------
 * Public shop:
 *   1. POST /create-checkout   -> creates a Stripe Checkout Session for a photo, returns the payment URL
 *                                  (pass orderType: "digital" or "print" — print adds shipping address
 *                                  collection and charges PRINT_PRICE_CENTS instead of the digital price)
 *   1b. GET /photo             -> public metadata for one photo (name, category, prices) — powers photo.html
 *   2. GET  /get-download      -> verifies payment with Stripe, then streams the real file from R2 (digital orders)
 *   2b. GET /print/fulfill     -> verifies payment with Stripe, then places the order with Prodigi (print orders)
 *   2c. GET /print/asset       -> streams a full-res original to Prodigi using a short-lived one-time
 *                                  token generated by print/fulfill — Prodigi needs a public URL to fetch
 *                                  the print file, so this is scoped to a single order and expires quickly.
 *
 * Private client galleries (senior photo delivery, etc.):
 *   3. POST /album/access      -> checks a passkey against an album, returns the list of photos if valid
 *   4. GET  /album/photo       -> streams one photo from R2, only if the passkey (sent as a header) checks out
 *   5. POST /clients/access    -> resolves a passkey: master key -> full album directory,
 *                                  a client's own passkey -> just their album's slug. Powers the
 *                                  Client Work page, so entering any valid passkey there gets you
 *                                  straight to the right gallery.
 *
 * Client intake:
 *   6. POST /contact/inquiry   -> emails you (via Resend) when someone submits the intake form
 *
 * Every client album has its own passkey. Your ALBUM_MASTER_KEY secret works as a passkey
 * for EVERY album, so you always have access without needing to remember each client's key.
 */

const PHOTOS = {
  "DSC_1975": { name: "Drumline Energy", priceCents: 2000, category: "events", caption: "Drumline Energy · Event", r2Key: "originals/DSC_1975.jpg" },
  "DSC_1993": { name: "Brass in Motion", priceCents: 2000, category: "events", caption: "Brass in Motion · Event", r2Key: "originals/DSC_1993.jpg" },
  "DSC_2809": { name: "Focused on the Beat", priceCents: 2000, category: "events", caption: "Focused on the Beat · Event", r2Key: "originals/DSC_2809.jpg" },
  "DSC_4179": { name: "Marching in Formation", priceCents: 2000, category: "events", caption: "Marching in Formation · Event", r2Key: "originals/DSC_4179.jpg" },
  "DSC_4180": { name: "Plumes in a Row", priceCents: 2000, category: "events", caption: "Plumes in a Row · Event", r2Key: "originals/DSC_4180.jpg" },
  "DSC_1491": { name: "Bass Drum Line", priceCents: 2000, category: "events", caption: "Bass Drum Line · Event", r2Key: "originals/DSC_1491.jpg" },
  "DSC_2221": { name: "Silhouette at Sunset", priceCents: 2000, category: "events", caption: "Silhouette at Sunset · Event", r2Key: "originals/DSC_2221.jpg" },
  "DSC_5294": { name: "Halftime Show", priceCents: 2000, category: "events", caption: "Halftime Show · Event", r2Key: "originals/DSC_5294.jpg" },
  "DSC_4297": { name: "Brass Lineup", priceCents: 2000, category: "events", caption: "Brass Lineup · Event", r2Key: "originals/DSC_4297.jpg" },
  "DSC_2603": { name: "War Paint", priceCents: 2000, category: "events", caption: "War Paint · Event", r2Key: "originals/DSC_2603.jpg" },
  "DSC_4493": { name: "Field Formation", priceCents: 2000, category: "events", caption: "Field Formation · Event", r2Key: "originals/DSC_4493.jpg" },
  "DSC_5516": { name: "Miata in the Fog", priceCents: 2000, category: "portraits", caption: "Miata in the Fog · Portrait", r2Key: "originals/DSC_5516.jpg" },
  "DSC_5074": { name: "Framed in Branches", priceCents: 2000, category: "portraits", caption: "Framed in Branches · Portrait", r2Key: "originals/DSC_5074.jpg" },
  "DSC_5032": { name: "Golden Hour Portrait", priceCents: 2000, category: "portraits", caption: "Golden Hour Portrait · Portrait", r2Key: "originals/DSC_5032.jpg" },
  "DSC_5533": { name: "Hay Bale Portrait", priceCents: 2000, category: "portraits", caption: "Hay Bale Portrait · Portrait", r2Key: "originals/DSC_5533.jpg" },
  "DSC_5538": { name: "Portrait on the Farm", priceCents: 2000, category: "portraits", caption: "Portrait on the Farm · Portrait", r2Key: "originals/DSC_5538.jpg" },
  "DSC_4677": { name: "Crossing the Burn", priceCents: 2000, category: "nature", caption: "Crossing the Burn · Nature", r2Key: "originals/DSC_4677.jpg" },
  "DSC_1325": { name: "Trail Marker in the Fog", priceCents: 2000, category: "nature", caption: "Trail Marker in the Fog · Nature", r2Key: "originals/DSC_1325.jpg" },
  "DSC_4721": { name: "Behind the Falls", priceCents: 2000, category: "nature", caption: "Behind the Falls · Nature", r2Key: "originals/DSC_4721.jpg" },
  "DSC_9847": { name: "View from the Ridge", priceCents: 2000, category: "nature", caption: "View from the Ridge · Nature", r2Key: "originals/DSC_9847.jpg" },
  "DSC_1344": { name: "Peaks Above the Clouds", priceCents: 2000, category: "nature", caption: "Peaks Above the Clouds · Nature", r2Key: "originals/DSC_1344.jpg" },
  "DSC_4666": { name: "Burned Forest Bridge", priceCents: 2000, category: "nature", caption: "Burned Forest Bridge · Nature", r2Key: "originals/DSC_4666.jpg" },
  "DSC_4798": { name: "Night Sky Over the Ridge", priceCents: 2000, category: "nature", caption: "Night Sky Over the Ridge · Nature", r2Key: "originals/DSC_4798.jpg" },
  "DSC_9709": { name: "Cliffside Forest", priceCents: 2000, category: "nature", caption: "Cliffside Forest · Nature", r2Key: "originals/DSC_9709.jpg" },
  "DSC_2104": { name: "Snowy Mountain Range", priceCents: 2000, category: "nature", caption: "Snowy Mountain Range · Nature", r2Key: "originals/DSC_2104.jpg" },
  "DSC_9436": { name: "Mountain Lake Inlet", priceCents: 2000, category: "nature", caption: "Mountain Lake Inlet · Nature", r2Key: "originals/DSC_9436.jpg" },
  "DSC_4834": { name: "Blooms on the Summit", priceCents: 2000, category: "nature", caption: "Blooms on the Summit · Nature", r2Key: "originals/DSC_4834.jpg" },
  "DSC_4789": { name: "Mount Borah Trailhead", priceCents: 2000, category: "nature", caption: "Mount Borah Trailhead · Nature", r2Key: "originals/DSC_4789.jpg" },
  "DSC_9800": { name: "Driftwood on the Riverbank", priceCents: 2000, category: "nature", caption: "Driftwood on the Riverbank · Nature", r2Key: "originals/DSC_9800.jpg" },
  "DSC_4731": { name: "Chukar on the Ridge", priceCents: 2000, category: "nature", caption: "Chukar on the Ridge · Nature", r2Key: "originals/DSC_4731.jpg" },
  "DSC_1089": { name: "Cloud Inversion at Dusk", priceCents: 2000, category: "nature", caption: "Cloud Inversion at Dusk · Nature", r2Key: "originals/DSC_1089.jpg" },
  "DSC_4842": { name: "Trail to the Summit", priceCents: 2000, category: "nature", caption: "Trail to the Summit · Nature", r2Key: "originals/DSC_4842.jpg" },
  "DSC_2129": { name: "Bogus Basin Summit", priceCents: 2000, category: "nature", caption: "Bogus Basin Summit · Nature", r2Key: "originals/DSC_2129.jpg" },
  "DSC_4709": { name: "Katydid on the Trail", priceCents: 2000, category: "nature", caption: "Katydid on the Trail · Nature", r2Key: "originals/DSC_4709.jpg" },
  "DSC_9527": { name: "Backcountry Cabin", priceCents: 2000, category: "nature", caption: "Backcountry Cabin · Nature", r2Key: "originals/DSC_9527.jpg" },
  "DSC_1063": { name: "Ridge Above the Clouds", priceCents: 2000, category: "nature", caption: "Ridge Above the Clouds · Nature", r2Key: "originals/DSC_1063.jpg" },
  "DSC_4830": { name: "Alpine Wildflowers", priceCents: 2000, category: "nature", caption: "Alpine Wildflowers · Nature", r2Key: "originals/DSC_4830.jpg" },
  "DSC_5261": { name: "Table Rock Under the Stars", priceCents: 2000, category: "nature", caption: "Table Rock Under the Stars · Nature", r2Key: "originals/DSC_5261.jpg" },
  "DSC_9501": { name: "Forest Stream", priceCents: 2000, category: "nature", caption: "Forest Stream · Nature", r2Key: "originals/DSC_9501.jpg" },
  "DSC_9628": { name: "Fireweed in Bloom", priceCents: 2000, category: "nature", caption: "Fireweed in Bloom · Nature", r2Key: "originals/DSC_9628.jpg" },
  "DSC_9517": { name: "Squirrel with a Pinecone", priceCents: 2000, category: "nature", caption: "Squirrel with a Pinecone · Nature", r2Key: "originals/DSC_9517.jpg" },
  "DSC_9794": { name: "Autumn on the Ridge", priceCents: 2000, category: "nature", caption: "Autumn on the Ridge · Nature", r2Key: "originals/DSC_9794.jpg" },
  "DSC_0707": { name: "Sawtooth Range at Dusk",        priceCents: 2000, category: "nature",    caption: "Sawtooth Range · Nature",   r2Key: "originals/DSC_0707.jpg" },
  "DSC_0720": { name: "Sawtooth Valley Sunset",        priceCents: 2000, category: "nature",    caption: "Sawtooth Valley · Nature",  r2Key: "originals/DSC_0720.jpg" },
  "DSC_9351": { name: "High Desert Ridgeline",         priceCents: 2000, category: "nature",    caption: "High Desert Ridgeline · Nature", r2Key: "originals/DSC_9351.jpg" },
  "DSC_9546": { name: "Marsh Life",                    priceCents: 2000, category: "nature",    caption: "Marsh Life · Wildlife",     r2Key: "originals/DSC_9546.jpg" },
  "DSC_4872": { name: "Ridgeline Layers",              priceCents: 2000, category: "nature",    caption: "Ridgeline Layers · Nature", r2Key: "originals/DSC_4872.jpg" },
  "DSC_4784": { name: "Backcountry Camp",              priceCents: 2000, category: "nature",    caption: "Backcountry Camp · Nature", r2Key: "originals/DSC_4784.jpg" },
  "DSC_4983": { name: "Evening Light",                 priceCents: 2000, category: "nature",    caption: "Evening Light · Nature",    r2Key: "originals/DSC_4983.jpg" },
  "DSC_5497": { name: "Foggy Morning Portrait",        priceCents: 2000, category: "portraits", caption: "Foggy Morning · Portrait",  r2Key: "originals/DSC_5497.jpg" },
  "DSC_2218": { name: "Boise Gems - Drummer",          priceCents: 2000, category: "events",    caption: "Boise Gems · Event",        r2Key: "originals/DSC_2218.jpg" },
  "DSC_2266": { name: "Boise Gems - Horn Player",       priceCents: 2000, category: "events",    caption: "Boise Gems · Event",        r2Key: "originals/DSC_2266.jpg" }
};

// ---- Fine-art print offering (single size/style for now) ----
// GLOBAL-HPR-16X24 is Hahnemühle Photo Rag, 16x24" — a 2:3 ratio that exactly
// matches a DSLR's native 3:2 aspect, so the full photo prints edge-to-edge
// with no cropping or padding. Prodigi's cost is ~$33 (print + US shipping);
// $80 leaves a healthy margin after that and Stripe's fee.
const PRINT_SKU = "GLOBAL-HPR-16X24";
const PRINT_PRICE_CENTS = 8000;
const PRINT_ASSET_TOKEN_TTL_SECONDS = 60 * 60 * 48; // 48 hours — plenty for Prodigi to fetch + retry

export default {
  async fetch(request, env) {
    const url = new URL(request.url);
    const cors = corsHeaders(env.ALLOWED_ORIGIN);

    // Preflight
    if (request.method === "OPTIONS") {
      return new Response(null, { headers: cors });
    }

    try {
      if (url.pathname === "/create-checkout" && request.method === "POST") {
        return await createCheckout(request, env, cors);
      }
      if (url.pathname === "/photo" && request.method === "GET") {
        return await getPhotoInfo(url, env, cors);
      }
      if (url.pathname === "/get-download" && request.method === "GET") {
        return await getDownload(url, env, cors);
      }
      if (url.pathname === "/album/access" && request.method === "POST") {
        return await albumAccess(request, env, cors);
      }
      if (url.pathname === "/album/photo" && request.method === "GET") {
        return await albumPhoto(request, url, env, cors);
      }
      if (url.pathname === "/clients/access" && request.method === "POST") {
        return await clientsAccess(request, env, cors);
      }
      if (url.pathname === "/contact/inquiry" && request.method === "POST") {
        return await contactInquiry(request, env, cors);
      }
      if (url.pathname === "/print/asset" && request.method === "GET") {
        return await printAsset(url, env, cors);
      }
      if (url.pathname === "/print/fulfill" && request.method === "GET") {
        return await printFulfill(url, env, cors);
      }
      return new Response("Not found", { status: 404, headers: cors });
    } catch (err) {
      return new Response(JSON.stringify({ error: err.message }), {
        status: 500,
        headers: { ...cors, "Content-Type": "application/json" }
      });
    }
  }
};

function corsHeaders(allowedOrigin) {
  return {
    "Access-Control-Allow-Origin": allowedOrigin || "*",
    "Access-Control-Allow-Methods": "GET, POST, OPTIONS",
    "Access-Control-Allow-Headers": "Content-Type, X-Album-Key"
  };
}

// ---- Hash a passkey with SHA-256 so raw passkeys are never stored ----
async function hashKey(key) {
  const data = new TextEncoder().encode(key.trim());
  const hashBuffer = await crypto.subtle.digest("SHA-256", data);
  return Array.from(new Uint8Array(hashBuffer)).map(b => b.toString(16).padStart(2, "0")).join("");
}

// ---- Check whether a submitted key is your personal master key ----
function isMasterKey(env, submittedKey) {
  return Boolean(
    submittedKey && env.ALBUM_MASTER_KEY && submittedKey.trim() === env.ALBUM_MASTER_KEY.trim()
  );
}

// ---- Check a submitted passkey against an album's stored hash OR your master key ----
async function checkAlbumAccess(env, slug, submittedKey) {
  if (!submittedKey) return { ok: false, album: null };

  // Master key always works, for any album
  if (isMasterKey(env, submittedKey)) {
    const albumRaw = await env.ALBUM_KV.get(`album:${slug}`);
    if (!albumRaw) return { ok: false, album: null };
    return { ok: true, album: JSON.parse(albumRaw) };
  }

  const albumRaw = await env.ALBUM_KV.get(`album:${slug}`);
  if (!albumRaw) return { ok: false, album: null };
  const album = JSON.parse(albumRaw);

  const submittedHash = await hashKey(submittedKey);
  if (submittedHash === album.passkeyHash) {
    return { ok: true, album };
  }
  return { ok: false, album: null };
}

// ---- Check the passkey and, if valid, return the album's photo list ----
async function albumAccess(request, env, cors) {
  const { slug, key } = await request.json();
  if (!slug || !key) {
    return new Response(JSON.stringify({ error: "Missing slug or key" }), {
      status: 400, headers: { ...cors, "Content-Type": "application/json" }
    });
  }

  const { ok, album } = await checkAlbumAccess(env, slug, key);
  if (!ok) {
    return new Response(JSON.stringify({ error: "Incorrect passkey" }), {
      status: 403, headers: { ...cors, "Content-Type": "application/json" }
    });
  }

  return new Response(JSON.stringify({
    ok: true,
    clientName: album.clientName,
    photos: album.photoKeys.map(k => ({
      file: k.split("/").pop(),
    }))
  }), { headers: { ...cors, "Content-Type": "application/json" } });
}

// ---- Stream one photo from R2, only after re-checking the passkey ----
async function albumPhoto(request, url, env, cors) {
  const slug = url.searchParams.get("slug");
  const file = url.searchParams.get("file");
  const key = request.headers.get("X-Album-Key");

  if (!slug || !file || !key) {
    return new Response(JSON.stringify({ error: "Missing slug, file, or key" }), {
      status: 400, headers: { ...cors, "Content-Type": "application/json" }
    });
  }

  const { ok, album } = await checkAlbumAccess(env, slug, key);
  if (!ok) {
    return new Response(JSON.stringify({ error: "Incorrect passkey" }), {
      status: 403, headers: { ...cors, "Content-Type": "application/json" }
    });
  }

  const r2Key = album.photoKeys.find(k => k.endsWith(`/${file}`));
  if (!r2Key) {
    return new Response(JSON.stringify({ error: "Photo not in this album" }), {
      status: 404, headers: { ...cors, "Content-Type": "application/json" }
    });
  }

  const object = await env.PHOTOS_BUCKET.get(r2Key);
  if (!object) {
    return new Response(JSON.stringify({ error: "File missing from storage" }), {
      status: 404, headers: { ...cors, "Content-Type": "application/json" }
    });
  }

  const download = url.searchParams.get("download") === "1";
  return new Response(object.body, {
    headers: {
      ...cors,
      "Content-Type": "image/jpeg",
      ...(download ? { "Content-Disposition": `attachment; filename="${file}"` } : {})
    }
  });
}

// ---- Read every album out of KV, as {slug, entry} pairs ----
async function listAllAlbumEntries(env) {
  const entries = [];
  let cursor;
  do {
    const page = await env.ALBUM_KV.list({ prefix: "album:", cursor });
    for (const item of page.keys) {
      const raw = await env.ALBUM_KV.get(item.name);
      if (!raw) continue;
      entries.push({ slug: item.name.slice("album:".length), album: JSON.parse(raw) });
    }
    cursor = page.list_complete ? undefined : page.cursor;
  } while (cursor);
  return entries;
}

// ---- Resolve a passkey typed into the Client Work page ----
// Master key -> the full album directory. A client's own passkey -> just their slug,
// so clicking "Client Work" and entering their passkey takes them straight to their gallery.
async function clientsAccess(request, env, cors) {
  const { key } = await request.json();
  if (!key) {
    return new Response(JSON.stringify({ error: "Missing key" }), {
      status: 400, headers: { ...cors, "Content-Type": "application/json" }
    });
  }

  const entries = await listAllAlbumEntries(env);

  if (isMasterKey(env, key)) {
    const albums = entries.map(({ slug, album }) => ({
      slug,
      clientName: album.clientName,
      photoCount: album.photoKeys.length,
      coverFile: album.photoKeys[0] ? album.photoKeys[0].split("/").pop() : null
    }));
    return new Response(JSON.stringify({ ok: true, role: "master", albums }), {
      headers: { ...cors, "Content-Type": "application/json" }
    });
  }

  const submittedHash = await hashKey(key);
  const match = entries.find(({ album }) => album.passkeyHash === submittedHash);
  if (match) {
    return new Response(JSON.stringify({ ok: true, role: "client", slug: match.slug }), {
      headers: { ...cors, "Content-Type": "application/json" }
    });
  }

  return new Response(JSON.stringify({ error: "Incorrect passkey" }), {
    status: 403, headers: { ...cors, "Content-Type": "application/json" }
  });
}

// ---- Public metadata for one photo, for the product page ----
async function getPhotoInfo(url, env, cors) {
  const id = url.searchParams.get("id");
  const photo = PHOTOS[id];
  if (!photo) {
    return new Response(JSON.stringify({ error: "Photo not found" }), {
      status: 404, headers: { ...cors, "Content-Type": "application/json" }
    });
  }
  return new Response(JSON.stringify({
    id,
    name: photo.name,
    category: photo.category,
    caption: photo.caption,
    priceCents: photo.priceCents,
    printPriceCents: PRINT_PRICE_CENTS
  }), { headers: { ...cors, "Content-Type": "application/json" } });
}

// ---- Create a Stripe Checkout Session for one photo (digital download or print) ----
async function createCheckout(request, env, cors) {
  const { photoId, orderType } = await request.json();
  const photo = PHOTOS[photoId];
  const isPrint = orderType === "print";

  if (!photo) {
    return new Response(JSON.stringify({ error: "Unknown photo" }), {
      status: 400,
      headers: { ...cors, "Content-Type": "application/json" }
    });
  }

  const siteUrl = env.SITE_URL; // e.g. https://forytography.com

  const params = {
    mode: "payment",
    "line_items[0][price_data][currency]": "usd",
    "line_items[0][price_data][product_data][name]": isPrint
      ? `${photo.name} — 16x24 Fine Art Print`
      : `${photo.name} — Digital Download`,
    "line_items[0][price_data][unit_amount]": String(isPrint ? PRINT_PRICE_CENTS : photo.priceCents),
    "line_items[0][quantity]": "1",
    success_url: `${siteUrl}/success.html?session_id={CHECKOUT_SESSION_ID}&type=${isPrint ? "print" : "digital"}`,
    cancel_url: `${siteUrl}/index.html`,
    "metadata[photoId]": photoId,
    "metadata[orderType]": isPrint ? "print" : "digital",
    "managed_payments[enabled]": "false"
  };

  if (isPrint) {
    // Prints need a physical address — Prodigi currently only ships within the US for us.
    params["shipping_address_collection[allowed_countries][0]"] = "US";
  }

  const body = new URLSearchParams(params);

  const stripeRes = await fetch("https://api.stripe.com/v1/checkout/sessions", {
    method: "POST",
    headers: {
      "Authorization": `Bearer ${env.STRIPE_SECRET_KEY}`,
      "Content-Type": "application/x-www-form-urlencoded"
    },
    body: body.toString()
  });

  const session = await stripeRes.json();

  if (!stripeRes.ok) {
    return new Response(JSON.stringify({ error: session.error?.message || "Stripe error" }), {
      status: 400,
      headers: { ...cors, "Content-Type": "application/json" }
    });
  }

  return new Response(JSON.stringify({ url: session.url }), {
    headers: { ...cors, "Content-Type": "application/json" }
  });
}

// ---- Verify payment, then stream the real file from R2 ----
async function getDownload(url, env, cors) {
  const sessionId = url.searchParams.get("session_id");
  if (!sessionId) {
    return new Response(JSON.stringify({ error: "Missing session_id" }), {
      status: 400,
      headers: { ...cors, "Content-Type": "application/json" }
    });
  }

  const stripeRes = await fetch(`https://api.stripe.com/v1/checkout/sessions/${sessionId}`, {
    headers: { "Authorization": `Bearer ${env.STRIPE_SECRET_KEY}` }
  });
  const session = await stripeRes.json();

  if (!stripeRes.ok) {
    return new Response(JSON.stringify({ error: "Could not verify payment" }), {
      status: 400,
      headers: { ...cors, "Content-Type": "application/json" }
    });
  }

  if (session.payment_status !== "paid") {
    return new Response(JSON.stringify({ error: "Payment not completed" }), {
      status: 402,
      headers: { ...cors, "Content-Type": "application/json" }
    });
  }

  const photoId = session.metadata?.photoId;
  const photo = PHOTOS[photoId];
  if (!photo) {
    return new Response(JSON.stringify({ error: "Photo not found" }), {
      status: 404,
      headers: { ...cors, "Content-Type": "application/json" }
    });
  }

  const object = await env.PHOTOS_BUCKET.get(photo.r2Key);
  if (!object) {
    return new Response(JSON.stringify({ error: "File missing from storage" }), {
      status: 404,
      headers: { ...cors, "Content-Type": "application/json" }
    });
  }

  return new Response(object.body, {
    headers: {
      ...cors,
      "Content-Type": "image/jpeg",
      "Content-Disposition": `attachment; filename="${photoId}-forytography.jpg"`
    }
  });
}

// ---- Generate a random, hard-to-guess token for one-time Prodigi asset access ----
function generateToken() {
  return Array.from(crypto.getRandomValues(new Uint8Array(24)))
    .map(b => b.toString(16).padStart(2, "0")).join("");
}

// ---- Stream a full-res original to Prodigi, gated by a short-lived order-scoped token ----
// Prodigi requires a publicly reachable URL for print assets (no direct upload), so this
// trades the passkey-style auth used elsewhere for a token that's random, single-purpose,
// and expires quickly — generated only after a real Stripe payment, in printFulfill below.
async function printAsset(url, env, cors) {
  const token = url.searchParams.get("token");
  if (!token) {
    return new Response("Missing token", { status: 400, headers: cors });
  }

  const raw = await env.ALBUM_KV.get(`printtoken:${token}`);
  if (!raw) {
    return new Response("Invalid or expired token", { status: 403, headers: cors });
  }

  const { r2Key } = JSON.parse(raw);
  const object = await env.PHOTOS_BUCKET.get(r2Key);
  if (!object) {
    return new Response("File missing from storage", { status: 404, headers: cors });
  }

  return new Response(object.body, {
    headers: { ...cors, "Content-Type": "image/jpeg" }
  });
}

// ---- Verify payment, then place the order with Prodigi ----
async function printFulfill(url, env, cors) {
  const sessionId = url.searchParams.get("session_id");
  if (!sessionId) {
    return new Response(JSON.stringify({ error: "Missing session_id" }), {
      status: 400, headers: { ...cors, "Content-Type": "application/json" }
    });
  }

  const stripeRes = await fetch(`https://api.stripe.com/v1/checkout/sessions/${sessionId}`, {
    headers: { "Authorization": `Bearer ${env.STRIPE_SECRET_KEY}` }
  });
  const session = await stripeRes.json();

  if (!stripeRes.ok) {
    return new Response(JSON.stringify({ error: "Could not verify payment" }), {
      status: 400, headers: { ...cors, "Content-Type": "application/json" }
    });
  }
  if (session.payment_status !== "paid") {
    return new Response(JSON.stringify({ error: "Payment not completed" }), {
      status: 402, headers: { ...cors, "Content-Type": "application/json" }
    });
  }
  if (session.metadata?.orderType !== "print") {
    return new Response(JSON.stringify({ error: "Not a print order" }), {
      status: 400, headers: { ...cors, "Content-Type": "application/json" }
    });
  }

  const photoId = session.metadata?.photoId;
  const photo = PHOTOS[photoId];
  if (!photo) {
    return new Response(JSON.stringify({ error: "Photo not found" }), {
      status: 404, headers: { ...cors, "Content-Type": "application/json" }
    });
  }

  // Stripe sometimes attaches the collected address to shipping_details, other
  // times only to customer_details (e.g. when "billing same as shipping" is
  // checked) — fall back to whichever one is actually populated.
  const address = session.shipping_details?.address || session.customer_details?.address;
  const recipientName = session.shipping_details?.name || session.customer_details?.name;

  if (!address || !recipientName) {
    console.error("Missing shipping address:", JSON.stringify({ shipping: session.shipping_details, customer: session.customer_details }));
    await notifyPhotographerOfError(env,
      `Print order missing shipping address for ${photo.name}`,
      `Stripe session ${sessionId} was paid but no shipping address was found.\n\n` +
      `Customer: ${session.customer_details?.email || "unknown"}\n\n` +
      `You'll need to check the Stripe dashboard for this session and place the Prodigi order manually, or refund the customer.`
    );
    return new Response(JSON.stringify({ error: "Missing shipping address" }), {
      status: 400, headers: { ...cors, "Content-Type": "application/json" }
    });
  }

  const token = generateToken();
  await env.ALBUM_KV.put(
    `printtoken:${token}`,
    JSON.stringify({ r2Key: photo.r2Key }),
    { expirationTtl: PRINT_ASSET_TOKEN_TTL_SECONDS }
  );
  const assetUrl = `${env.SITE_WORKER_URL}/print/asset?token=${token}`;

  const prodigiRes = await fetch(`${env.PRODIGI_BASE_URL}/v4.0/orders`, {
    method: "POST",
    headers: {
      "X-API-Key": env.PRODIGI_API_KEY,
      "Content-Type": "application/json"
    },
    body: JSON.stringify({
      merchantReference: sessionId,
      idempotencyKey: sessionId,
      shippingMethod: "Standard",
      recipient: {
        name: recipientName,
        email: session.customer_details?.email,
        address: {
          line1: address.line1,
          line2: address.line2 || undefined,
          postalOrZipCode: address.postal_code,
          countryCode: address.country,
          townOrCity: address.city,
          stateOrCounty: address.state
        }
      },
      items: [{
        merchantReference: photoId,
        sku: PRINT_SKU,
        copies: 1,
        sizing: "fillPrintArea",
        assets: [{ printArea: "default", url: assetUrl }]
      }]
    })
  });

  const prodigiOrder = await prodigiRes.json();

  if (!prodigiRes.ok || (prodigiOrder.outcome !== "Created" && prodigiOrder.outcome !== "CreatedWithIssues" && prodigiOrder.outcome !== "AlreadyExists")) {
    console.error("Prodigi order error:", JSON.stringify(prodigiOrder));
    await notifyPhotographerOfError(env,
      `Print order failed for ${photo.name}`,
      `Stripe session ${sessionId} was paid ($${(PRINT_PRICE_CENTS / 100).toFixed(2)}) but the Prodigi order failed to create.\n\n` +
      `Photo: ${photo.name} (${photoId})\nCustomer: ${recipientName} <${session.customer_details?.email || "no email"}>\n\n` +
      `Prodigi response: ${JSON.stringify(prodigiOrder)}\n\n` +
      `You'll likely need to place this print order manually in the Prodigi dashboard, or refund the customer in Stripe.`
    );
    return new Response(JSON.stringify({ error: "Payment succeeded, but there was a problem placing the print order. I've been notified and will follow up." }), {
      status: 502, headers: { ...cors, "Content-Type": "application/json" }
    });
  }

  return new Response(JSON.stringify({ ok: true, orderId: prodigiOrder.order?.id }), {
    headers: { ...cors, "Content-Type": "application/json" }
  });
}

function escapeHtml(str) {
  return String(str).replace(/[&<>"']/g, (c) => ({
    "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;"
  }[c]));
}

// ---- Send yourself a plain operational alert via Resend (e.g. a failed print order) ----
async function notifyPhotographerOfError(env, subject, plainTextBody) {
  try {
    await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: {
        "Authorization": `Bearer ${env.RESEND_API_KEY}`,
        "Content-Type": "application/json"
      },
      body: JSON.stringify({
        from: env.FROM_EMAIL || "Forytography Inquiries <onboarding@resend.dev>",
        to: [env.CONTACT_EMAIL],
        subject: `[Forytography site] ${subject}`,
        text: plainTextBody
      })
    });
  } catch (err) {
    console.error("Failed to send error notification email:", err.message);
  }
}

// ---- Email the photographer when someone submits the client intake form ----

async function contactInquiry(request, env, cors) {
  const body = await request.json();

  // Honeypot: real visitors never see or fill this field. If it's filled,
  // silently pretend success so bots don't learn to look elsewhere.
  if (body.website) {
    return new Response(JSON.stringify({ ok: true }), {
      headers: { ...cors, "Content-Type": "application/json" }
    });
  }

  const name = (body.name || "").trim();
  const email = (body.email || "").trim();
  const vision = (body.vision || "").trim();

  if (!name || !email || !vision || !email.includes("@")) {
    return new Response(JSON.stringify({ error: "Please fill in your name, a valid email, and a bit about what you're looking for." }), {
      status: 400, headers: { ...cors, "Content-Type": "application/json" }
    });
  }

  const fields = [
    ["Name", name],
    ["Email", email],
    ["Phone", body.phone],
    ["Session type", body.sessionType],
    ["Preferred date(s)", body.dates],
    ["Location", body.location],
    ["Group size", body.groupSize],
    ["Budget range", body.budget],
    ["How they heard about you", body.referral],
    ["Instagram / reference link", body.reference],
  ].filter(([, value]) => value && String(value).trim());

  const rowsHtml = fields.map(([label, value]) =>
    `<tr><td style="padding:4px 12px 4px 0;color:#6B7A5E;font-weight:600;white-space:nowrap;vertical-align:top;">${escapeHtml(label)}</td><td style="padding:4px 0;">${escapeHtml(value)}</td></tr>`
  ).join("");

  const html = `
    <div style="font-family:Georgia,serif;color:#1F2620;max-width:560px;">
      <h2 style="font-family:Arial,sans-serif;">New inquiry from ${escapeHtml(name)}</h2>
      <table style="border-collapse:collapse;font-size:14px;">${rowsHtml}</table>
      <p style="margin-top:20px;font-size:14px;"><strong>What they're looking for:</strong><br>${escapeHtml(vision).replace(/\n/g, "<br>")}</p>
    </div>
  `;

  const resendRes = await fetch("https://api.resend.com/emails", {
    method: "POST",
    headers: {
      "Authorization": `Bearer ${env.RESEND_API_KEY}`,
      "Content-Type": "application/json"
    },
    body: JSON.stringify({
      from: env.FROM_EMAIL || "Forytography Inquiries <onboarding@resend.dev>",
      to: [env.CONTACT_EMAIL],
      reply_to: email,
      subject: `New inquiry from ${name}`,
      html
    })
  });

  if (!resendRes.ok) {
    console.error("Resend error:", await resendRes.text());
    return new Response(JSON.stringify({ error: "Could not send your inquiry right now. Please try again shortly." }), {
      status: 502, headers: { ...cors, "Content-Type": "application/json" }
    });
  }

  return new Response(JSON.stringify({ ok: true }), {
    headers: { ...cors, "Content-Type": "application/json" }
  });
}
